### ISSUE TITLE
Three-term-recrusive for order greater than 10

### ISSUE THREAD

**Issue by Jinsongl** [jonathf/chaospy#196]
Dear @jonathf 
Thanks very much for your help in advance!

I got a ValueError when applying chaospy.orth_ttr() with order higher than 10.
Following are my code and error message:
>>> import chaospy as cp
>>> dist = cp.Normal()
>>> poly = cp.orth_ttr(5,dist)
>>> poly = cp.orth_ttr(10,dist)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/chaospy/orthogonal/three_terms_recursion.py", line 97, in orth_ttr
    numpy.max(order), dist, normed=normed)
  File "/usr/local/lib/python3.7/site-packages/chaospy/quadrature/recurrence/stieltjes.py", line 143, in analytical_stieljes
    orth = chaospy.poly.polynomial(orth[1:]).T
  File "/usr/local/lib/python3.7/site-packages/numpoly/construct/polynomial.py", line 130, in polynomial
    dtype=dtype,
  File "/usr/local/lib/python3.7/site-packages/numpoly/construct/compose.py", line 35, in compose_polynomial_array
    ], axis=0)
  File "/usr/local/lib/python3.7/site-packages/numpoly/array_function/concatenate.py", line 46, in concatenate
    [array.values for array in arrays], axis=axis, out=out)
  File "/usr/local/lib/python3.7/site-packages/numpoly/array_function/concatenate.py", line 46, in <listcomp>
    [array.values for array in arrays], axis=axis, out=out)
  File "/usr/local/lib/python3.7/site-packages/numpoly/baseclass.py", line 321, in values
    buffer=self.data
ValueError: ':' is not an allowed character in buffer field names

Packages (Versions)
   chaospy  (3.1.0)
   numpoly(0.1.4)
   scipy (1.4.1)
   numpy (1.18.1)

Python: 3.7.4
OS: Mac Catalina 10.15.2

The above codes run successfully with Python 2.7.16

Thanks,
Jason

**Comment by jonathf** [comment]
Yes, I am aware of the bug, but haven't gotten around to push it.

Done it now. Check out version 3.1.1.

**Comment by jonathf** [comment]
Assuming problem solve. Feel free to reopen if incorrect.
