### ISSUE TITLE
Multivariate Normal Expected Value

### ISSUE THREAD

**Issue by JacobDowns** [jonathf/chaospy#214]
I am attempting to take the expected value of a multivariate normal distribution.

```python
x0 = np.zeros(10)
P0 = np.eye(10)
dist = chaospy.MvNormal(x0, P0)
expected = chaospy.E(dist)
```
This results in

```shell
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    expected = chaospy.E(dist)
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/descriptives/expected.py", line 42, in E
    moments = dist.mom(poly.exponents.T, **kws)
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass.py", line 333, in mom
    out = [evaluation.evaluate_moment(self, kdata, {}) for kdata in K.T]
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass.py", line 333, in <listcomp>
    out = [evaluation.evaluate_moment(self, kdata, {}) for kdata in K.T]
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/distributions/evaluation/moment.py", line 94, in evaluate_moment
    out = distribution._mom(k_data, **parameters)
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/distributions/collection/mv_normal.py", line 88, in _mom
    for idx, kdx in enumerate(bindex(k, dim=len(C), sort="G")):
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/bertran/indices.py", line 69, in bindex
    indices = _bindex(start, stop, dim, cross_truncation)
  File "/home/jake/.local/lib/python3.6/site-packages/chaospy/bertran/indices.py", line 108, in _bindex
    indices = indices[numpy.all(indices <= stop, -1)]
ValueError: operands could not be broadcast together with shapes (4,2) (10,) 
```

Thank you,
Jake

**Comment by jonathf** [comment]
Yes, the `bindex` function have had a bug. I've been working to fix it today.
Try to update to `chaospy==3.2.4` and `numpoly=0.1.11`. It should hopefully be fixed there.

**Comment by JacobDowns** [comment]
Thank you, m

**Comment by JacobDowns** [comment]
Thank you, much appreciated!
