### ISSUE TITLE
Leja quadrature problem

### ISSUE THREAD

**Issue by dlouk** [jonathf/chaospy#313]
Hi Jonathan,

I get `AttributeError: module 'numpoly' has no attribute 'variable'` whenever trying to call `chaospy.quad_leja` or `chaospy.generate_quadrature(order, distribution, rule="leja")`. The problem appears for all orders and distributions that I have tested. 

Chaospy version is 4.2.2, Scipy version is 1.5.4, Numpy version is 1.18.1.The full traceback is:

```
Traceback (most recent call last):

  File "<ipython-input-14-d6f92b02f8af>", line 1, in <module>
    runfile('/home/dilu/Documents/Python_scripts/test_Chaospy/leja_tests.py', wdir='/home/dilu/Documents/Python_scripts/test_Chaospy')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/dilu/Documents/Python_scripts/test_Chaospy/leja_tests.py", line 15, in <module>
    abscissas, weights = chaospy.generate_quadrature(order, distribution, rule="leja")

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/quadrature/frontend.py", line 150, in generate_quadrature
    n_max=n_max,

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/quadrature/frontend.py", line 219, in _generate_quadrature
    abscissas, weights = quad_function(order, dist, **parameters)

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/quadrature/leja.py", line 85, in quad_leja
    abscissas = [dist.lower, dist.mom(1).flatten(), dist.upper]

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass/distribution.py", line 573, in mom
    out = [self._get_mom(kdata) for kdata in K.T]

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass/distribution.py", line 573, in <listcomp>
    out = [self._get_mom(kdata) for kdata in K.T]

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass/distribution.py", line 596, in _get_mom
    ret_val = float(self._mom(kdata, **parameters))

  File "/home/dilu/.local/lib/python3.6/site-packages/chaospy/distributions/baseclass/lower_upper.py", line 95, in _mom
    poly = numpoly.variable(len(self))

AttributeError: module 'numpoly' has no attribute 'variable'

Any thoughts?
```

**Comment by jonathf** [comment]
Try running:

    pip install -U numpoly

Let me know if that solves the problem.

**Comment by dlouk** [comment]
yeap, that did the trick!
