### ISSUE TITLE
AttributeError: module 'numpoly' has no attribute 'variable'

### ISSUE THREAD

**Issue by moja84** [jonathf/chaospy#331]
Hello, 
I am using chaospy and uncertainpy to determine Sobol' indices. Unfortunately I get an error. I also tried the example [https://uncertainpy.readthedocs.io/en/latest/examples/coffee_cup.html](https://uncertainpy.readthedocs.io/en/latest/examples/coffee_cup.html) and get the same error. Since I don't know where to address the bug (here or at uncertainpy) I have the reported the same bug at the uncertainpy side ([https://github.com/simetenn/uncertainpy/issues/48](https://github.com/simetenn/uncertainpy/issues/48). 
On Fedora 33 with chaospy-4.2.5, and Python 3.8.7

> Traceback (most recent call last):
File "test_chaospy.py", line 40, in
data = UQ.quantify(seed=10)
File "/usr/local/lib/python3.8/site-packages/uncertainpy/uncertainty.py", line 415, in quantify
data = self.polynomial_chaos(uncertain_parameters=uncertain_parameters,
File "/usr/local/lib/python3.8/site-packages/uncertainpy/uncertainty.py", line 702, in polynomial_chaos
self.data = self.uncertainty_calculations.polynomial_chaos(
File "/usr/local/lib/python3.8/site-packages/uncertainpy/core/uncertainty_calculations.py", line 1351, in polynomial_chaos
self.create_PCE_collocation(uncertain_parameters=uncertain_parameters,
File "/usr/local/lib/python3.8/site-packages/uncertainpy/core/uncertainty_calculations.py", line 621, in create_PCE_collocation
P = cp.orth_ttr(polynomial_order, distribution)
File "/usr/local/lib/python3.8/site-packages/chaospy-4.2.5-py3.8.egg/chaospy/orthogonal/three_terms_recurrence.py", line 111, in orth_ttr
_, polynomials, norms, = chaospy.stieltjes(numpy.max(order), dist)
File "/usr/local/lib/python3.8/site-packages/chaospy-4.2.5-py3.8.egg/chaospy/recurrence/stieltjes.py", line 68, in stieltjes
return analytical_stieltjes(order=order, dist=dist)
File "/usr/local/lib/python3.8/site-packages/chaospy-4.2.5-py3.8.egg/chaospy/recurrence/stieltjes.py", line 165, in analytical_stieltjes
var = numpoly.variable(dimensions)
AttributeError: module 'numpoly' has no attribute 'variable'

I hope someone can help me. Many thanks in advance. 

Greets Momme

**Comment by jonathf** [comment]
Numpoly is an external dependency. What version is it?
And what happens after you do `pip install -U numpoly`?

**Comment by moja84** [comment]
Thanks for the hint. I could solve the problem with installing using the git clone command described in [https://numpoly.readthedocs.io/en/master/installation.html](https://numpoly.readthedocs.io/en/master/installation.html).
Now everything works fine :)
