### ISSUE TITLE
Expectation for TruncNormal() results in error

### ISSUE THREAD

**Issue by ahenkes1** [jonathf/chaospy#333]
Hi @jonathf,

I have some trouble calculating the expectation for `TruncNormal()` in ChaosPy. The sample code works for `Normal()` distributions, but exchanging it to `TruncNormal()` results in the following error:

```
Traceback (most recent call last):
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/baseclass/distribution.py", line 573, in mom
    out = [self._get_mom(kdata) for kdata in K.T]
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/baseclass/distribution.py", line 573, in <listcomp>
    out = [self._get_mom(kdata) for kdata in K.T]
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/baseclass/distribution.py", line 596, in _get_mom
    ret_val = float(self._mom(kdata, **parameters))
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/operators/joint.py", line 156, in _mom
    raise chaospy.UnsupportedFeature(
chaospy.UnsupportedFeature: Shared dependencies across joint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxx/trunc_test.py", line 40, in <module>
    expected_pce2 = chp.E(poly=approx, dist=dist_r)
  File "xxx/venv/lib/python3.8/site-packages/chaospy/descriptives/expected.py", line 42, in E
    moments = dist.mom(poly.exponents.T, **kws)
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/baseclass/distribution.py", line 580, in mom
    out = [chaospy.approximate_moment(self, kdata) for kdata in K.T]
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/baseclass/distribution.py", line 580, in <listcomp>
    out = [chaospy.approximate_moment(self, kdata) for kdata in K.T]
  File "xxx/venv/lib/python3.8/site-packages/chaospy/distributions/approximation.py", line 194, in approximate_moment
    assert len(distribution) == 1, "only 1-D distributions support approximate moment."
AssertionError: only 1-D distributions support approximate moment.

```

Here is the sample code:

```
import chaospy as chp
import numpy as np

mu_1 = 10
mu_2 = 0.1
mu_3 = 0.2

sig_1 = 0.1 * mu_1
sig_2 = 0.1 * mu_2
sig_3 = 0.1 * mu_3

dist_1 = chp.TruncNormal(mu=mu_1, sigma=sig_1)
dist_2 = chp.TruncNormal(mu=mu_2, sigma=sig_2)
dist_3 = chp.TruncNormal(mu=mu_3, sigma=sig_3)

dist_q = chp.J(dist_1, dist_2, dist_3)

dist_r = chp.Iid(chp.TruncNormal(mu=0.0, sigma=1.0), length=3)

poly = chp.orth_ttr(order=1, dist=dist_r)

nodes_r, weight_r = chp.generate_quadrature(order=1,
                                            dist=dist_r,
                                            rule='gaussian')

nodes_q = dist_q.inv(dist_r.fwd(nodes_r))
weights_q = weight_r * dist_q.pdf(nodes_q) / dist_r.pdf(nodes_r)

solves = np.zeros((nodes_q[0].size, 3))
counter_pce = 0
for ab in nodes_q.T:
    solves[counter_pce, :] = 2 * ab
    counter_pce = counter_pce + 1

approx = chp.fit_quadrature(orth=poly,
                            nodes=nodes_r,
                            weights=weights_q,
                            solves=solves)

expected_pce2 = chp.E(poly=approx, dist=dist_r)
deviation_pce2 = chp.Std(poly=approx, dist=dist_r)
```

Is this a bug or is it a general problem which I am overseeing at the moment?

**Comment by jonathf** [comment]
Hey,

I believe I know what that relates to, but will need to take a closer look first to be sure.
I will attend to it next week.

In the mean time, can you post your `chaospy.__version__` number? Also let me know if you have installed from the repo master branch or through pip.

**Comment by ahenkes1** [comment]
Hi,

my version is **4.2.5** and I installed it via **pip**.

**Comment by ahenkes1** [comment]
With 4.2.7 everything is working, thank you very much. It is working for generalized PCE as well as standard PCE.
