### ISSUE TITLE
Joint distributions with dependencies and numpy.poly1d

### ISSUE THREAD

**Issue by davidovitch** [jonathf/chaospy#38]
I am trying to construct a joint distribution in which the second depends on the first. This is also used in the examples created here https://github.com/jp5000/PCE-4-WindEnergy/blob/master/Example/8)_Example.ipynb. I am running the development branch of my [fork](https://github.com/davidovitch/chaospy/tree/development).

```python
import numpy as np
import chaospy as cp
from matplotlib import pyplot as plt

# manually calculate the what np.poly1d is supposed to do
def calc_poly(poly, x):
    exp = 0.0
    degree = len(poly)
    for i, coeff in enumerate(poly):
        exp += (coeff*np.power(x, degree-i))
    return exp

def p1(x):
    return ( 1. + (1.4)**2./(0.75*x + 3.8)**2.0)**0.5

def p2(x):
    return ( 1. + (1.4)**2./(0.75*x + 3.8)**2.0)

# we have the following dependency
dist1_x_rng = np.arange(0, 30, 1)
mu = p1(dist1_x_rng)
sigma = p2(dist1_x_rng)

# fit a polynomial to it
mu_pfit = np.poly1d(np.polyfit(dist1_x_rng, mu, 6))
sigma_pfit = np.poly1d(np.polyfit(dist1_x_rng, sigma, 6))

# is calc_poly doing what it is supposed to do?
assert np.allclose(calc_poly(mu_pfit, dist1_x_rng), mu_pfit(dist1_x_rng))

#plt.plot(dist1_x_rng, mu)
#plt.plot(dist1_x_rng, calc_poly(mu_pfit, dist1_x_rng))
#assert np.allclose(calc_poly(mu_pfit, dist1_x_rng), mu)

dist_1 = cp.Normal()
# indicate the dependency using the np.poly1d object
dist_2a = cp.Lognormal(mu=mu_pfit(dist_1), sigma=sigma_pfit(dist_1))
# or using calc_poly
dist_2b = cp.Lognormal(mu=calc_poly(mu_pfit, dist_1), sigma=calc_poly(sigma_pfit, dist_1))
# or using the polynomials directly
dist_2c = cp.Lognormal(mu=p1(dist_1), sigma=p2(dist_1))

# join the distribution and sample, but this will fail
dist_Q_a = cp.J(dist_1, dist_2a)
sample_Q_a = dist_Q_a.sample(size=512, rule='H')
# see below for the lengthy traceback

# works
dist_Q_b = cp.J(dist_1, dist_2b)
sample_Q_b = dist_Q_b.sample(size=512, rule='H')

# works
dist_Q_c = cp.J(dist_1, dist_2c)
sample_Q_c = dist_Q_c.sample(size=512, rule='H')
```

I think this example worked at some point with Chaospy but I haven't figured out when it broke. I will also add this as a test case in PR #31. I have not figured out yet why it fails with ```numpy.poly1d```, but would like to create an issue for it in case someone knows already what is going on here.

**Comment by davidovitch** [comment]
and here's the traceback when running from the development branch of my [fork](https://github.com/davidovitch/chaospy/tree/development) (which contains some fixes for the operators, see also PR #31):

```
>>> sample_Q_a = dist_Q.sample(size=512, rule='H')
Traceback (most recent call last):

  File "<ipython-input-28-9ce5645bf302>", line 2, in <module>
    sample_Q_a = dist_Q.sample(size=512, rule='H')

  File "davidovitch/chaospy/src/chaospy/dist/baseclass.py", line 273, in sample
    out = chaospy.dist.sampler.samplegen(size_, self, rule, antithetic)

  File "davidovitch/chaospy/src/chaospy/dist/sampler/generator.py", line 134, in samplegen
    X = trans(X, verbose=verbose)

  File "davidovitch/chaospy/src/chaospy/dist/baseclass.py", line 199, in inv
    return chaospy.dist.rosenblatt.inv(self, q, maxiter, tol, **kws)

  File "davidovitch/chaospy/src/chaospy/dist/rosenblatt.py", line 38, in inv
    out, graph = dist.graph.run(q, "inv", maxiter=maxiter, tol=tol)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 269, in run
    out = self(x, self.root)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 156, in __call__
    return self._call(*args, **kwargs)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 400, in inv_call
    out[:] = dist._ppf(q, self)

  File "davidovitch/chaospy/src/chaospy/dist/joint.py", line 117, in _ppf
    out[i] = graph(q[i], graph.dists[key])

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 156, in __call__
    return self._call(*args, **kwargs)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 400, in inv_call
    out[:] = dist._ppf(q, self)

  File "davidovitch/chaospy/src/chaospy/dist/operators/multiply.py", line 61, in _ppf
    uloc = (uloc*(num > 0) + (1.-uloc)*(num <= 0))

  File "davidovitch/chaospy/src/chaospy/dist/baseclass.py", line 459, in __gt__
    return chaospy.dist.operators.trunk(X, self)

  File "davidovitch/chaospy/src/chaospy/dist/operators/trunkation.py", line 113, in trunk
    return Trunk(left, right)

  File "davidovitch/chaospy/src/chaospy/dist/operators/trunkation.py", line 26, in __init__
    assert numpy.all(left < right.range()[1])

  File "davidovitch/chaospy/src/chaospy/dist/baseclass.py", line 123, in range
    x = chaospy.dist.approx.find_interior_point(self)

  File "davidovitch/chaospy/src/chaospy/dist/approx.py", line 421, in find_interior_point
    bnd = dist.range(numpy.zeros(len(dist)))

  File "davidovitch/chaospy/src/chaospy/dist/baseclass.py", line 130, in range
    out, graph = self.graph.run(x, "range")

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 269, in run
    out = self(x, self.root)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 156, in __call__
    return self._call(*args, **kwargs)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 432, in range_call
    _ = dist._bnd(x, self)

  File "davidovitch/chaospy/src/chaospy/dist/operators/power.py", line 38, in _bnd
    bnd = num**graph(y, dist)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 156, in __call__
    return self._call(*args, **kwargs)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 432, in range_call
    _ = dist._bnd(x, self)

  File "davidovitch/chaospy/src/chaospy/dist/operators/addition.py", line 46, in _bnd
    lower, upper = graph((xloc.T-num.T).T, dist)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 156, in __call__
    return self._call(*args, **kwargs)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 432, in range_call
    _ = dist._bnd(x, self)

  File "davidovitch/chaospy/src/chaospy/dist/operators/multiply.py", line 33, in _bnd
    num, dist = graph.keys["right"], graph.dists["left"]

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 611, in __getitem__
    return self.getitem(key)

  File "davidovitch/chaospy/src/chaospy/dist/graph.py", line 657, in getitem
    raise KeyError()

KeyError
```

**Comment by jonathf** [comment]
There seems to be parts of the development branch that wasn't updated from fixing bug #33. which was causing some trouble.

I've update both `master` and `development` now so the premise is a little different. Do you mind updating and trying again? I am not able to reproduce.

**Comment by davidovitch** [comment]
Checked against updated ```master``` and ```development``` branches (starting from a clean ```git clone``` to make sure I don't have any leftovers that any previous attempts), but still got the same results. If you can not reproduce I will try again later on a different Windows machine (running Linux here).

**Comment by jonathf** [comment]
Okay, sorry, yes I am able to reproduce it now.

I am not quite sure what is going on here. I will have to take a closer look.

**Comment by jonathf** [comment]
The core of the problem lies in the fact that `numpy.poly1d` explicitly casts the base into a numpy array:
```
>>> mu_pfit(dist_1).prm["left"].prm
{'left': <chaospy.dist.operators.addition.Add at 0x7f0f0ce31410>,
 'right': array(<chaospy.dist.cores.normal object at 0x7f0f299db6d0>, dtype=object)}
```
I am not sure if this is something that I can actually fix in any simple way. I think you are stuck using the manual calculation as long as it does this.

**Comment by jonathf** [comment]
I consider the issue as resolved.

**Comment by davidovitch** [comment]
Thanks! Since the work-around is rather simple I think this sounds rather reasonable.
