### ISSUE TITLE
distribution addition fails

### ISSUE THREAD

**Issue by regislebrun** [jonathf/chaospy#97]
This script
```
import chaospy as ch

d=ch.uniform()
sum=d+d+d
sum.pdf(0.8)
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/baseclass.py", line 233, in pdf
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/baseclass.py", line 198, in run
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/main.py", line 61, in call
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/baseclass.py", line 160, in __call__
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/calling/range_.py", line 27, in range_call
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/operators/addition.py", line 120, in _bnd
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/containers.py", line 65, in __getitem__
  File "/usr/lib/python3.5/site-packages/chaospy-2.3.2-py3.5.egg/chaospy/distributions/graph/containers.py", line 113, in getitem
KeyError
```

Régis

**Comment by jonathf** [comment]
The reason your snippet fails is that Chaospy tries to decipher the joint distribution `d1+d2+d3`, and fails when it tries to resolve the three dimensional problem in the context of a one-dimensional variable.
(Chaospy does not support convolution of distributions if you were wondering.)

From our point of view, obviously the question is a bit different when
`d1=d2=d3` because you could reduce your problem into::

    sum = 3*d

but that is just a question of how smart `chaospy` is to figure that out. The answer is that it doesn't. It understand that `d+d = 2*d`, but it can not go from `(2*d)+d = 3*d`. It is a limitation in the current implementation.

If however you do want to deal with the more general `d1+d2+d3` where each variable is different, this can be done as follows::

    d1 = ch.Uniform()
    d2 = d1+ch.Uniform()
    d3 = d2+ch.Uniform()
    sum = ch.J(d1, d2, d3)
    sum.pdf([0.6, 0.7, 0.8])

This is then resolved as a three dimensional random variable.
